= Operator Design

== API Group and Version

The CRDs that the operator is handling are living in these groups and versions:

[cols=",",options="header",]
|===
a|
Property

a|
Value

|API group |`syn.tools`
|API version |`v1alpha1`
|===

The API documentation of these CRDs can be found under xref:references/crds-html.adoc[References/CRDs].

== CRD Description

A high-level description about the idea behind the objects:

[cols=",",options="header",]
|===

|CRD
|Description

|_Tenant_
a|When a tenant is created, a _GitRepo_ object
is created to create the *tenant configuration repository*.

|_GitRepo_
a|Git repository management (CRUD repositories on GitLab, GitHub and Gitea).
Lieutenant manages the CR objects and queries the status fields to get
the status.

The Operator manages the following objects:

_GitRepo_

* Create Git repository +
** By default on http://git.vshn.net/[git.vshn.net] GitLab
** Supported are GitLab, GitHub and Gitea APIs
** SSH key delivered by Steward is configured as deploy key
* Delete Git repository
* Update Git repository when configuration changes
** Only SSH deploy key change supported

|_Cluster_
a|When a _Cluster_ object is created:

* a _GitRepo_ object is created to create the *cluster catalog
configuration repository*.

When a _Cluster_ object is deleted:

* All created objects are deleted by `ownerReference` mechanisms

|===
