# permissions for end users to edit clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-editor-role
rules:
  - apiGroups:
      - syn.tools
    resources:
      - clusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - syn.tools
    resources:
      - clusters/status
    verbs:
      - get
