# permissions for end users to view tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-viewer-role
rules:
  - apiGroups:
      - syn.tools
    resources:
      - tenants
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - syn.tools
    resources:
      - tenants/status
    verbs:
      - get
