apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.syn.tools
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.displayName
    name: Display Name
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: syn.tools
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Tenant is the Schema for the tenants API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TenantSpec defines the desired state of Tenant
          properties:
            displayName:
              description: DisplayName is the display name of the tenant.
              type: string
            gitRepoTemplate:
              description: GitRepoTemplate Template for managing the GitRepo object.
                If not set, no  GitRepo object will be created.
              properties:
                apiSecretRef:
                  description: APISecretRef reference to secret containing connection
                    information
                  properties:
                    name:
                      description: Name is unique within a namespace to reference
                        a secret resource.
                      type: string
                    namespace:
                      description: Namespace defines the space within which the secret
                        name must be unique.
                      type: string
                  type: object
                deployKeys:
                  additionalProperties:
                    description: DeployKey defines an SSH key to be used for git operations.
                    properties:
                      key:
                        type: string
                      type:
                        type: string
                      writeAccess:
                        type: boolean
                    type: object
                  description: DeployKeys optional list of SSH deploy keys. If not
                    set, not deploy keys will be configured
                  type: object
                path:
                  description: Path to Git repository
                  type: string
                repoName:
                  description: RepoName ame of Git repository
                  type: string
              required:
              - apiSecretRef
              - path
              - repoName
              type: object
            gitRepoURL:
              description: GitRepoURL git repository storing the tenant configuration.
                If this is set, no gitRepoTemplate is needed.
              type: string
          required:
          - displayName
          type: object
        status:
          description: TenantStatus defines the observed state of Tenant
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
