apiVersion: apps/v1
kind: Deployment
metadata:
  name: lieutenant-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lieutenant-operator
  template:
    metadata:
      labels:
        name: lieutenant-operator
    spec:
      serviceAccountName: lieutenant-operator
      containers:
        - name: lieutenant-operator
          image: docker.io/projectsyn/lieutenant-operator:v0.0.3
          command:
          - lieutenant-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "lieutenant-operator"
