apiVersion: syn.tools/v1alpha1
kind: GitRepo
metadata:
  name: example-gitrepo2
spec:
  tenantRef:
    name: blubb
    namespace: syn-lieutenant
  apiSecretRef:
    name: example-secret
  path: cluster/subgroup
  repoName: somethingelse
  deployKeys:
    test:
      type: ssh-ed25519
      key: AAAAC3NzaC1lZDI1NTE5AAAAIJ22mHNYfSPnLAj8YiKa0RmxafD9r5nEUquizay7xh3s
      writeAccess: true
    test2:
      type: ssh-rsa
      key: AAAAB3NzaC1yc2EAAAADAQABAAACAQDRZgli29uGJa1Rd366viBTyQn5Z1FYhcD5N9LP+J6e1jP2mi0SaLYfgGub3S19CL20iHkI1kfCgUXcM0jtfcGptc5AR8DWt51PvZ0iurkgY2OKpHoUs+lhm/7PrGbCvbje7d3QxWNgxLyXWAXP1ypLKnxpmlUJ681SqWqPy8CouJAhjUDA5i5f7puh/uuVrGFMsoBOloyIg9vuV+BHXHrkeBjZk+MGgaWwKbXO83TcsrJfeKk3mAEkxmSWEar0NosI+4u7ikYH2zSXyjdAC0wPiEzJpt93ztaeo1RFXhN78fghAcpx5/ffWQOg9M/45ju54J86pvXCrSSJ8Wg+9Ui3mW40qqbf6422KZ62XAdbwiWvgW5FgbHyzw7AAo/m+D2kIZVImjLUwCpbBDpWWR+f62HorXZWSMcDuTCHN0kuqke1uESs3GTAlS2wINOGA6YSN9ap/0OHn/04fGGe1OSacPGwfmUZ6k3wkYLpWIQcQC5NLk/VuB9WRmWictYl/cUeopA2naN9Vl5HE6wouw3rP6W5AeZp//7Hnbjx1/MrlCzPUij+tUR5oN7woZYQXkv1KvLBZls3sEkbk39Ix1jva4R6M4UdlQUgc0re5WabnmHkA8Wd03t82oGUtFVAjpFH8uJD+K/NPD2sWN4EzQzsGW+5PLrFn/HJzx0Yob+mJw==
      writeAccess: false
