apiVersion: syn.tools/v1alpha1
kind: Cluster
metadata:
  name: ae3oso
spec:
  displayName: Big Corp. Production Cluster
  gitRepoTemplate:
    path: cluster
    repoName: test
    apiSecretRef:
      name: example-secret
      namespace: syn-lieutenant
    deployKeys:
      test:
        type: ssh-ed25519
        key: AAAAC3NzaC1lZDI1NTE5AAAAIJ22mHNYfSPnLAj8YiKa0RmxafD9r5nEUquizay7xh3s
        writeAccess: true
  tenantRef:
    name: aezoo6
  tokenLifeTime: 4h
  facts:
    distribution: openshift3
    cloud: cloudscale
    region: rma1
