apiVersion: syn.tools/v1alpha1
kind: Tenant
metadata:
  name: t-aezoo6
spec:
  displayName: Big Corp.
  gitRepoTemplate:
    path: tenant
    repoName: test
    apiSecretRef:
      name: example-secret
      namespace: syn-lieutenant
    deployKeys:
      test:
        type: ssh-ed25519
        key: AAAAC3NzaC1lZDI1NTE5AAAAIJ22mHNYfSPnLAj8YiKa0RmxafD9r5nEUquizay7xh3s
        writeAccess: true
