apiVersion: apps/v1
kind: Deployment
metadata:
  name: lieutenant-operator
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: lieutenant-operator
      containers:
        - name: lieutenant-operator
          image: docker.io/projectsyn/lieutenant-operator:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: lieutenant-operator
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
