apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: lieutenant-operator
  app.kubernetes.io/part-of: project-syn
images:
  - name: docker.io/projectsyn/lieutenant-operator
    newTag: 1.1.2
resources:
  - deployment.yaml
  - role_binding.yaml
  - role.yaml
  - service_account.yaml
