# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/syn.tools_clusters.yaml
  - bases/syn.tools_gitrepos.yaml
  - bases/syn.tools_tenants.yaml
  - bases/syn.tools_tenanttemplates.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge: []

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
