name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_yaml
          - docs-vale
    steps:
      - uses: actions/checkout@v2
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Generate
        run: make generate
      - name: No diff
        run: git diff --exit-code
      - name: Test code
        run: make test
      - name: Build Image
        run: make docker-build

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
